name: deploy vue
on: 
  push: 
    branch: 
      - master

jobs: 
  deploy-app: 
     runs-on: ubuntu-latest
     steps: 
      - name: check out the code to the main server
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with: 
          version: 7
          run_install: false
      - name: Use node.js 18.x
        uses: actions/checkout@v3
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: build a code
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build
      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER_NAME}}
          key: ${{secrets.SSH_KEY}}
          source: "./dist/*"
          target: "/var/www/html"
          strip_components: 1